id: 60-second-linux
name: 60-second Linux analysis
nixpkgs:
  version: "380be19fbd2d9079f677978361792cb25e8a3635" # nixos-22.05 branch
  packages:
    - coreutils
    - util-linux
    - procps
    - sysstat
system_prompt: |
  ### 60-second Linux analysis

  Please analyze the following Linux system diagnostic output. Focus on identifying any performance issues, errors, or notable system characteristics.

  - Be concise but comprehensive
  - Start with a 1-sentence overview and the key finding
  - Prefer bullet points where helpful
  - Keep the total length to 2-3 short paragraphs (including bullets)

  When recommending actions, prioritize practical steps.
commands:
  - command: uptime
    description: System uptime, load averages
  - command: vmstat 1
    description: Virtual memory statistics
  - command: mpstat -P ALL 1
    description: CPU utilization per core
  - command: pidstat 1
    description: Per-process CPU usage
  - command: iostat -xz 1
    description: Extended I/O statistics
  - command: free -m
    description: Memory usage
  - command: sar -n DEV 1
    description: Network device statistics
  - command: sar -n TCP,ETCP 1
    description: TCP counters and errors
  - command: top -b -n 1
    description: Top processes snapshot
  - command: dmesg
    description: Kernel ring buffer
