name: Build app

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build app ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            os: linux
            arch: amd64
          - runner: ubuntu-24.04-arm
            os: linux
            arch: arm64
          - runner: macos-13
            os: darwin
            arch: amd64
          - runner: macos-15
            os: darwin
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Show environment
        run: |
          go version
          go env GOOS GOARCH

      - name: Build
        run: |
          mkdir -p dist
          GOFLAGS="-trimpath" go build -ldflags="-s -w" -o dist/gradient-engineer.${{ matrix.os }}.${{ matrix.arch }} ./app

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradient-engineer.${{ matrix.os }}.${{ matrix.arch }}
          path: dist/gradient-engineer.${{ matrix.os }}.${{ matrix.arch }}
          if-no-files-found: error
          compression-level: 0


